using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace TEngine.Editor.UITK
{
    /// <summary>
    /// UIToolkit 绑定代码生成器。
    /// 扫描 [Q]/[OnClick]/[OnChange]/[Bind]/[BindCommand]，生成 .bindgen.cs。
    /// </summary>
    public static class UITKBindingGenerator
    {
        private const string GENERATED_SUFFIX = ".bindgen.cs";
        private const string HEADER = "// <auto-generated by UITKBindingGenerator>\n// Do not modify manually.\n";

        [MenuItem("TEngine/UITK/Generate All Bindings", priority = 100)]
        public static void GenerateAll()
        {
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();
            int count = 0;

            foreach (var assembly in assemblies)
            {
                // 只扫描热更程序集
                if (!assembly.GetName().Name.Contains("GameLogic") &&
                    !assembly.GetName().Name.Contains("GameBase"))
                    continue;

                foreach (var type in assembly.GetTypes())
                {
                    if (TryGenerateForType(type))
                        count++;
                }
            }

            AssetDatabase.Refresh();
            Debug.Log($"[UITKBindingGenerator] Generated {count} binding file(s).");
        }

        [MenuItem("TEngine/UITK/Generate Binding (Selected)", priority = 101)]
        public static void GenerateSelected()
        {
            var selected = Selection.activeObject as MonoScript;
            if (selected == null)
            {
                Debug.LogWarning("[UITKBindingGenerator] Please select a C# script file.");
                return;
            }

            var type = selected.GetClass();
            if (type == null)
            {
                Debug.LogWarning($"[UITKBindingGenerator] Cannot get type from {selected.name}.");
                return;
            }

            if (TryGenerateForType(type))
            {
                AssetDatabase.Refresh();
                Debug.Log($"[UITKBindingGenerator] Generated binding for {type.Name}.");
            }
            else
            {
                Debug.Log($"[UITKBindingGenerator] {type.Name} has no binding attributes, skipped.");
            }
        }

        private static bool TryGenerateForType(Type type)
        {
            // 必须继承 UITKWindow 或 UITKWidget
            if (!IsUITKType(type)) return false;

            var flags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly;

            // 收集信息
            var qFields = new List<QFieldInfo>();
            var onClickMethods = new List<EventMethodInfo>();
            var onChangeMethods = new List<EventMethodInfo>();
            var bindFields = new List<BindFieldInfo>();
            var bindCommands = new List<BindCommandInfo>();

            // 扫描字段
            foreach (var field in type.GetFields(flags))
            {
                var qAttr = field.GetCustomAttribute<GameLogic.QAttribute>();
                if (qAttr != null)
                {
                    string uxmlName = qAttr.Name ?? UITKNamingHelper.ToKebabCase(field.Name);
                    qFields.Add(new QFieldInfo
                    {
                        FieldName = field.Name,
                        TypeName = field.FieldType.Name,
                        TypeFullName = field.FieldType.FullName,
                        UxmlName = uxmlName,
                    });
                }

                var bindAttr = field.GetCustomAttribute<GameLogic.BindAttribute>();
                if (bindAttr != null)
                {
                    bindFields.Add(new BindFieldInfo
                    {
                        FieldName = field.Name,
                        TypeName = field.FieldType.Name,
                        Path = bindAttr.Path,
                        Mode = bindAttr.Mode,
                        Format = bindAttr.Format,
                    });
                }

                var cmdAttr = field.GetCustomAttribute<GameLogic.BindCommandAttribute>();
                if (cmdAttr != null)
                {
                    bindCommands.Add(new BindCommandInfo
                    {
                        FieldName = field.Name,
                        CommandName = cmdAttr.CommandName,
                    });
                }
            }

            // 扫描方法
            foreach (var method in type.GetMethods(flags))
            {
                var clickAttr = method.GetCustomAttribute<GameLogic.OnClickAttribute>();
                if (clickAttr != null)
                {
                    string target = clickAttr.Target ?? UITKNamingHelper.MethodNameToTarget(method.Name);
                    onClickMethods.Add(new EventMethodInfo { MethodName = method.Name, UxmlTarget = target, Sound = clickAttr.Sound });
                }

                var changeAttr = method.GetCustomAttribute<GameLogic.OnChangeAttribute>();
                if (changeAttr != null)
                {
                    onChangeMethods.Add(new EventMethodInfo { MethodName = method.Name, UxmlTarget = changeAttr.Target });
                }
            }

            // 无绑定内容则跳过
            if (qFields.Count == 0 && onClickMethods.Count == 0 && onChangeMethods.Count == 0 &&
                bindFields.Count == 0 && bindCommands.Count == 0)
                return false;

            // 找到源文件路径
            string sourcePath = FindSourceFile(type);
            if (string.IsNullOrEmpty(sourcePath) || sourcePath.Contains(".bindgen.")) return false;

            // 生成代码
            string code = GenerateCode(type, qFields, onClickMethods, onChangeMethods, bindFields, bindCommands);

            // 写入 .bindgen.cs
            string outputPath = sourcePath.Replace(".cs", GENERATED_SUFFIX);
            File.WriteAllText(outputPath, code, Encoding.UTF8);

            return true;
        }

        private static string GenerateCode(Type type, List<QFieldInfo> qFields, List<EventMethodInfo> clickMethods,
            List<EventMethodInfo> changeMethods, List<BindFieldInfo> bindFields, List<BindCommandInfo> bindCommands)
        {
            var sb = new StringBuilder();
            sb.AppendLine(HEADER);
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine.UIElements;");
            sb.AppendLine();

            string ns = type.Namespace;
            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(ns) ? "    " : "        ";
            string classIndent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.AppendLine($"{classIndent}partial class {type.Name}");
            sb.AppendLine($"{classIndent}{{");

            // __UITKAutoBind
            sb.AppendLine($"{indent}protected override void __UITKAutoBind(UnityEngine.UIElements.VisualElement root)");
            sb.AppendLine($"{indent}{{");
            foreach (var q in qFields)
            {
                sb.AppendLine($"{indent}    {q.FieldName} = root.Q<{q.TypeName}>(\"{q.UxmlName}\");");
            }
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();

            // __UITKAutoBindEvents
            // 生成 click 委托缓存字段
            foreach (var click in clickMethods)
            {
                var field = qFields.FirstOrDefault(q => q.UxmlName == click.UxmlTarget);
                if (field != null && click.Sound != "")
                {
                    sb.AppendLine($"{indent}private Action __click_{field.FieldName};");
                }
            }
            sb.AppendLine();

            sb.AppendLine($"{indent}protected override void __UITKAutoBindEvents()");
            sb.AppendLine($"{indent}{{");
            foreach (var click in clickMethods)
            {
                var field = qFields.FirstOrDefault(q => q.UxmlName == click.UxmlTarget);
                if (field == null) continue;

                if (click.Sound == "")
                {
                    // 静音：直接绑定方法
                    sb.AppendLine($"{indent}    {field.FieldName}.AddToClassList(\"__uitk-has-sound\");");
                    sb.AppendLine($"{indent}    {field.FieldName}.clicked += {click.MethodName};");
                }
                else
                {
                    // 有音效（默认或指定）：生成包装委托
                    string soundArg = click.Sound == null ? "null" : $"\\\"{click.Sound}\\\"";
                    sb.AppendLine($"{indent}    {field.FieldName}.AddToClassList(\"__uitk-has-sound\");");
                    sb.AppendLine($"{indent}    __click_{field.FieldName} = () => {{ UITKModule.Instance.ClickSoundHandler?.OnButtonClick({field.FieldName}, {soundArg}); {click.MethodName}(); }};");
                    sb.AppendLine($"{indent}    {field.FieldName}.clicked += __click_{field.FieldName};");
                }
            }
            foreach (var change in changeMethods)
            {
                var field = qFields.FirstOrDefault(q => q.UxmlName == change.UxmlTarget);
                if (field != null)
                    sb.AppendLine($"{indent}    {field.FieldName}.RegisterValueChangedCallback({change.MethodName});");
            }
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();

            // __UITKAutoUnbindEvents
            sb.AppendLine($"{indent}protected override void __UITKAutoUnbindEvents()");
            sb.AppendLine($"{indent}{{");
            foreach (var click in clickMethods)
            {
                var field = qFields.FirstOrDefault(q => q.UxmlName == click.UxmlTarget);
                if (field == null) continue;

                if (click.Sound == "")
                {
                    sb.AppendLine($"{indent}    {field.FieldName}.clicked -= {click.MethodName};");
                }
                else
                {
                    sb.AppendLine($"{indent}    if (__click_{field.FieldName} != null) {field.FieldName}.clicked -= __click_{field.FieldName};");
                }
            }
            foreach (var change in changeMethods)
            {
                var field = qFields.FirstOrDefault(q => q.UxmlName == change.UxmlTarget);
                if (field != null)
                    sb.AppendLine($"{indent}    {field.FieldName}.UnregisterValueChangedCallback({change.MethodName});");
            }
            sb.AppendLine($"{indent}}}");

            // MVVM: __UITKAutoBindViewModel (如果有 [Bind] 或 [BindCommand])
            if (bindFields.Count > 0 || bindCommands.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}private List<Action> __mvvmUnbindActions = new List<Action>();");
                sb.AppendLine();
                sb.AppendLine($"{indent}protected override void __UITKAutoBindMVVM(GameLogic.ViewModelBase vm)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    var typedVm = vm;");

                foreach (var bind in bindFields)
                {
                    string propAccess = $"(({type.Name}ViewModel)vm).{bind.Path}";
                    string formatExpr = bind.Format != null
                        ? $"string.Format(\"{bind.Format}\", v)"
                        : "v?.ToString() ?? \"\"";

                    sb.AppendLine($"{indent}    // Bind: {bind.FieldName} ← {bind.Path}");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        var prop = (({type.Name}ViewModel)vm).{bind.Path};");
                    sb.AppendLine($"{indent}        Action<object> update = _ =>");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            var val = prop.Value;");
                    if (bind.Format != null)
                        sb.AppendLine($"{indent}            if ({bind.FieldName} is Label lbl) lbl.text = string.Format(\"{bind.Format}\", val);");
                    else
                        sb.AppendLine($"{indent}            if ({bind.FieldName} is Label lbl) lbl.text = val?.ToString() ?? \"\";");
                    sb.AppendLine($"{indent}        }};");
                    sb.AppendLine($"{indent}        prop.OnValueChanged += v => update(null);");
                    sb.AppendLine($"{indent}        update(null);");
                    sb.AppendLine($"{indent}        __mvvmUnbindActions.Add(() => prop.OnValueChanged -= v => update(null));");
                    sb.AppendLine($"{indent}    }}");
                }

                foreach (var cmd in bindCommands)
                {
                    sb.AppendLine($"{indent}    // BindCommand: {cmd.FieldName} ← {cmd.CommandName}");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        var command = (({type.Name}ViewModel)vm).{cmd.CommandName};");
                    sb.AppendLine($"{indent}        if ({cmd.FieldName} is Button btn)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            btn.clicked += command.Execute;");
                    sb.AppendLine($"{indent}            Action canExecUpdate = () => btn.SetEnabled(command.CanExecute());");
                    sb.AppendLine($"{indent}            command.CanExecuteChanged += canExecUpdate;");
                    sb.AppendLine($"{indent}            canExecUpdate();");
                    sb.AppendLine($"{indent}            __mvvmUnbindActions.Add(() => {{ btn.clicked -= command.Execute; command.CanExecuteChanged -= canExecUpdate; }});");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}    }}");
                }

                sb.AppendLine($"{indent}}}");
                sb.AppendLine();
                sb.AppendLine($"{indent}protected override void __UITKAutoUnbindMVVM()");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    foreach (var action in __mvvmUnbindActions) action();");
                sb.AppendLine($"{indent}    __mvvmUnbindActions.Clear();");
                sb.AppendLine($"{indent}}}");
            }

            sb.AppendLine($"{classIndent}}}");

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static string FindSourceFile(Type type)
        {
            // 通过 GUID 搜索脚本文件
            string[] guids = AssetDatabase.FindAssets($"t:MonoScript {type.Name}");
            foreach (var guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (path.Contains(".bindgen.")) continue;  // 跳过已生成文件
                var script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                if (script != null && script.GetClass() == type)
                {
                    return path;
                }
            }

            // 回退：按文件名搜索
            string[] paths = AssetDatabase.FindAssets($"{type.Name} t:MonoScript");
            foreach (var guid in paths)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (path.Contains(".bindgen.")) continue;  // 跳过已生成文件
                if (Path.GetFileNameWithoutExtension(path) == type.Name)
                    return path;
            }

            Debug.LogWarning($"[UITKBindingGenerator] Source file not found for {type.FullName}");
            return null;
        }

        private static bool IsUITKType(Type type)
        {
            if (type.IsAbstract || !type.IsClass) return false;
            var current = type.BaseType;
            while (current != null)
            {
                if (current.Name == "UITKWindow" || current.Name == "UITKWidget")
                    return true;
                current = current.BaseType;
            }
            return false;
        }

        // ━━━ 数据结构 ━━━

        private class QFieldInfo
        {
            public string FieldName;
            public string TypeName;
            public string TypeFullName;
            public string UxmlName;
        }

        private class EventMethodInfo
        {
            public string MethodName;
            public string UxmlTarget;
            public string Sound; // null=默认, ""=静音, other=指定音效
        }

        private class BindFieldInfo
        {
            public string FieldName;
            public string TypeName;
            public string Path;
            public GameLogic.BindingMode Mode;
            public string Format;
        }

        private class BindCommandInfo
        {
            public string FieldName;
            public string CommandName;
        }
    }
}
