using UnityEngine;
using UnityEngine.UI;
using TEngine;
namespace Game.UI
{
	[UIRes(gen_UIRoleInfoWidget.ResTag, EUIResLoadType.AssetBundle)]
	public class gen_UIRoleInfoWidget : UIHolderObjectBase
	{
		public const string ResTag = "UIRoleInfoWidget";
		#region Generated by Script Tool

		[SerializeField]
		private Slider mSliderHp;
		public Slider SliderHp => mSliderHp;

		[SerializeField]
		private Text mTextHpValue;
		public Text TextHpValue => mTextHpValue;

		[SerializeField]
		private Slider mSliderMp;
		public Slider SliderMp => mSliderMp;

		[SerializeField]
		private Text mTextMpValue;
		public Text TextMpValue => mTextMpValue;

		[SerializeField]
		private Slider mSliderExp;
		public Slider SliderExp => mSliderExp;

		[SerializeField]
		private Text mTextExpValue;
		public Text TextExpValue => mTextExpValue;


		#endregion
	}
}
