using UnityEngine;
using UnityEngine.UI;
using TEngine;
namespace Game.UI
{
	[UIRes(gen_UIMonsterInfoWidget.ResTag, EUIResLoadType.AssetBundle)]
	public class gen_UIMonsterInfoWidget : UIHolderObjectBase
	{
		public const string ResTag = "UIMonsterInfoWidget";
		#region Generated by Script Tool

		[SerializeField]
		private RectTransform mRectName;
		public RectTransform RectName => mRectName;

		[SerializeField]
		private Slider mSliderHp;
		public Slider SliderHp => mSliderHp;

		[SerializeField]
		private Text mTextHpValue;
		public Text TextHpValue => mTextHpValue;

		[SerializeField]
		private RectTransform mRectInfo;
		public RectTransform RectInfo => mRectInfo;

		[SerializeField]
		private Text mTextMonsterAttr;
		public Text TextMonsterAttr => mTextMonsterAttr;

		#endregion
	}
}
