using UnityEngine;
using UnityEngine.UI;
using TEngine;
namespace Game.UI
{
	[UIRes(gen_LogUI.ResTag, EUIResLoadType.AssetBundle)]
	public class gen_LogUI : UIHolderObjectBase
	{
		public const string ResTag = "LogUI";
		#region Generated by Script Tool

		[SerializeField]
		private Text mTextError;
		public Text TextError => mTextError;

		[SerializeField]
		private Button mBtnClose;
		public Button BtnClose => mBtnClose;


		#endregion
	}
}
