using UnityEngine;
using Game.UI;
using TEngine;
namespace Game.UI
{
	[UIRes(gen_BattleMainUI.ResTag, EUIResLoadType.AssetBundle)]
	public class gen_BattleMainUI : UIHolderObjectBase
	{
		public const string ResTag = "BattleMainUI";
		#region Generated by Script Tool

		[SerializeField]
		private RectTransform mRectContainer;
		public RectTransform RectContainer => mRectContainer;

		[SerializeField]
		private RectTransform mRectItemTouch;
		public RectTransform RectItemTouch => mRectItemTouch;

		[SerializeField]
		private RectTransform mRectTopInfo;
		public RectTransform RectTopInfo => mRectTopInfo;

		[SerializeField]
		private gen_UIMonsterInfoWidget mUIMonsterInfoWidget;
		public gen_UIMonsterInfoWidget UIMonsterInfoWidget => mUIMonsterInfoWidget;

		#endregion
	}
}
