// <auto-generated by UITKBindingGenerator>
// Do not modify manually.

using System;
using System.Collections.Generic;
using UnityEngine.UIElements;

namespace GameLogic
{
    partial class TestMvvmAutoBindWindow
    {
        protected override void __UITKAutoBind(UnityEngine.UIElements.VisualElement root)
        {
            lblTitle = root.Q<Label>("lbl-title");
            lblCounter = root.Q<Label>("lbl-counter");
            inputName = root.Q<TextField>("input-name");
            sliderVolume = root.Q<Slider>("slider-volume");
            inputCounter = root.Q<TextField>("input-counter");
            btnIncrement = root.Q<Button>("btn-increment");
            btnClose = root.Q<Button>("btn-close");
        }

        protected override void __UITKAutoBindEvents()
        {
        }

        protected override void __UITKAutoUnbindEvents()
        {
        }

        protected override void __UITKAutoBindMVVM()
        {
            if (_vm == null) { TEngine.Log.Warning("[MVVM] TestMvvmAutoBindWindow._vm 为 null，已跳过自动绑定。请确认已在 OnCreate 中构造 ViewModel。"); return; }
            BindLabel(lblCounter, _vm.Counter, v => string.Format("Count: {0}", v));
            BindField(inputName, _vm.PlayerName, GameLogic.BindingMode.TwoWay);
            BindField(sliderVolume, _vm.Volume, GameLogic.BindingMode.TwoWay);
            BindField(inputCounter, _vm.Counter, new GameLogic.IntToStringConverter(), GameLogic.BindingMode.TwoWay);
            BindCommand(btnIncrement, _vm.IncrementCommand);
            BindCommand(btnClose, _vm.CloseCommand);
        }
    }
}
