// <auto-generated by UITKBindingGenerator>
// Do not modify manually.

using System;
using System.Collections.Generic;
using UnityEngine.UIElements;

namespace GameLogic
{
    partial class TestAutoBindWindow
    {
        protected override void __UITKAutoBind(UnityEngine.UIElements.VisualElement root)
        {
            lblTitle = root.Q<Label>("lbl-title");
            lblCount = root.Q<Label>("lbl-count");
            btnIncrement = root.Q<Button>("btn-increment");
            btnDecrement = root.Q<Button>("btn-decrement");
            inputName = root.Q<TextField>("input-name");
            lblNameEcho = root.Q<Label>("lbl-name-echo");
            btnClose = root.Q<Button>("btn-close");
        }

        protected override void __UITKAutoBindEvents()
        {
            btnIncrement.AddToClassList("__uitk-has-sound");
            btnIncrement.clicked += () => { UITKModule.Instance.ClickSoundHandler?.OnButtonClick(btnIncrement, null); OnBtnIncrement(); };
            btnDecrement.AddToClassList("__uitk-has-sound");
            btnDecrement.clicked += () => { UITKModule.Instance.ClickSoundHandler?.OnButtonClick(btnDecrement, null); OnBtnDecrement(); };
            btnClose.AddToClassList("__uitk-has-sound");
            btnClose.clicked += () => { UITKModule.Instance.ClickSoundHandler?.OnButtonClick(btnClose, null); OnBtnClose(); };
            inputName.RegisterValueChangedCallback(OnNameChanged);
        }

        protected override void __UITKAutoUnbindEvents()
        {
            btnIncrement.clicked -= OnBtnIncrement;
            btnDecrement.clicked -= OnBtnDecrement;
            btnClose.clicked -= OnBtnClose;
            inputName.UnregisterValueChangedCallback(OnNameChanged);
        }
    }
}
