// <auto-generated by UITKBindingGenerator>
// Do not modify manually.

using System;
using System.Collections.Generic;
using UnityEngine.UIElements;

namespace GameLogic
{
    partial class TestAutoBindWindow
    {
        private void __UITKAutoBind(VisualElement root)
        {
            lblTitle = root.Q<Label>("lbl-title");
            lblCount = root.Q<Label>("lbl-count");
            btnIncrement = root.Q<Button>("btn-increment");
            btnDecrement = root.Q<Button>("btn-decrement");
            inputName = root.Q<TextField>("input-name");
            lblNameEcho = root.Q<Label>("lbl-name-echo");
            btnClose = root.Q<Button>("btn-close");
        }

        private void __UITKAutoBindEvents()
        {
            btnIncrement.clicked += OnBtnIncrement;
            btnDecrement.clicked += OnBtnDecrement;
            btnClose.clicked += OnBtnClose;
            inputName.RegisterValueChangedCallback(OnNameChanged);
        }

        private void __UITKAutoUnbindEvents()
        {
            btnIncrement.clicked -= OnBtnIncrement;
            btnDecrement.clicked -= OnBtnDecrement;
            btnClose.clicked -= OnBtnClose;
            inputName.UnregisterValueChangedCallback(OnNameChanged);
        }
    }
}
